### ISSUE TITLE
_

### ISSUE THREAD

**Issue by justscribe** [colshrapnel/safemysql#29]

**Comment by GZep** [comment]
Используйте разметку кода.

Задача решается функцией parse.

**Comment by colshrapnel** [comment]
Я так и не увидел конкретную практическую задачу, которую решает этот код.
С задачей было бы гораздо проще.

Ну а предлагаемое решение нельзя использовать по одной простой причине - первый аргумент после запроса может быть обычным массивом с данными для плейсхолдера, без всяких выкрутасов.

**Comment by alexprey** [comment]
@colshrapnel я так понимаю, автор хочет сделать batch вставку данных в таблицу сделать

**Comment by NEOSCRIBE** [comment]
Проблема использования класса заключалась в том, что я хотел добавлять в вашу функцию любое количество параметров, а не иметь под параметр переменную.
Есть:
$db->query('INSERT INTO table_name (id, name, date) VALUES (?i, ?s, ?s)', $id, $name, $date);
А если мне неизвестно количество этих (?i, ?s, ?s). (или мне лень переписывать)
Т.е этот список переменных ($id, $name, $date), фиксирован! А в массив я могу легким движением руки добавить элемент и запрос полностью поменяется.
Или возьмем не INSERT.
$db->query('SELECT * FROM table_name WHERE id=?i AND name=?s', $id, $name);
Я хочу туда передать массив, а не заранее вбивать список из ($id, $name).
Если оно решается с помощью ?u/?a буду благодарен за пример.

**Comment by colshrapnel** [comment]
В целом да - это моя недоработка. Уже был тикет на эту тему. 
Но для INSERT и UPDATE все решается через `?u`
Дело в том что для вставки всегда можно обойтись строковым типом, для любых полей. 
Поэтому те поля, которые мы хотим передать в запрос, мы пишем в массив
```php
$insert = array(
    'id'   => $id,
    'name' => $name,
    'date' => $date,
);
```
и передаем этот массив в запрос через `?u`:
```php
$db->query("INSERT INTO ?n SET ?u", $table, $insert);
```
в дальнейшем мы можем как угодно менять массив на вставку  - он отработает без проблем.  К примеру, добавив одно поле
```php
$insert = array(
    'id'   => $id,
    'name' => $name,
    'date' => $date,
    'pass' => $pass,
);
```
- такой массив добавится в от же запрос без проблем.

Однако для селекта, увы, решения нет. Можно только сделать костыль с помощью call_userfunc_array

**Comment by colshrapnel** [comment]
@alexprey для батч вставки есть костыль через `parse()`
предполагая, что данные для вставки лежат в 2-d массиве `$data`, где каждая строка - это ассоциативный массив с данными каждой строки:
```php
$ins = array();
foreach ($data as $row) {
    $ins[] = $db->parse("(NULL,?s,?s, NOW())",$row['name'],$row['lastname']);
}
$instr = implode(",",$ins);
$db->query("INSERT INTO table VALUES ?p",$instr);
```
Но в новой версии я хочу сделать модификатор для размножения значений - `?an`, `?ai` и т.п. И как-то batch вставку под это тоже подвести.

**Comment by NEOSCRIBE** [comment]
Спасибо за ответ. 
Если для INSERT и UPDATE строк хватает, тогда наверное не стоит сильно заморачиватся насчет SELECT.

**Comment by GZep** [comment]
не лучше-ли для новой версии поменять плейсхолдеры:
```
?s - строка
:s - строки (текущий ?s)
?i - число
:i - числа
?n - имя поля
:n - имена полей
и т.д.
```

**Comment by colshrapnel** [comment]
@GZep двоеточие точно не подойдет - я хочу сделать именованные плейсхолдеры по типу ПДО-шных.
Про синтаксис я долго думал, и пока решил остановиться на модификаторе 'a' - то есть, плейсхолдер может быть двухбуквенным, типа ?ia (при этом ? должен быть синонимом ?s и тогда текущий ?a нормально ляжет в общую схему).

Но вообще идея со сменой символа мне нравится. Осталось придумать, какой не задействованный в запросе символ использовать...

**Comment by pafnuty** [comment]
@colshrapnel а вариант с двумя вопросительными знаками не рассматривали?
```
?s - строка
??s - строки (текущий ?a)
?i - число
??i - числа
?n - имя поля
??n - имена полей
и т.д.
```

**Comment by GZep** [comment]
@colshrapnel можно амперсанд (&) задействовать. Двоеточие мне нравится логическим соответствием для множеств.
> типа ?ia (при этом ? должен быть синонимом ?s
не совсем поняля идею.

На мой взгляд, проблема сейчас в том, что
```
?s - одна строка
?a - множество строк
?n - одно имя поля
```
и дальше логика ломается. так как для множества имен полей предложено:
```
?ns
```
в таком случае, почему __?a__, а не **?ss**

**Comment by colshrapnel** [comment]
@pafnuty с удвоением вопросительного знака - отличная идея! Мне нравится!
Впрочем, @GZep предложил не хуже - удваивать саму букву. Теперь только выбрать, какой вариант лучше :)

амперсанд - это оператор в мускуле, не годится. 
двоеточие, все-таки, в области составления запросов - это однозначно именованный плейсхолдер, воспринимается только так. 

Вообще, идея такая. Ввести именованные плейсхолдеры и - самое главное - дефолтные плейсхолдеры без указания типа (обрабатываются как строки). Ведь 99% данных - это строки! Поэтому можно писать просто ? или :name  не запариваться с типами. А тип писать только там, где строка не подходит:

    LIMIT ?i, ?i
    LIMIT :start?i, :per_page?i

**Comment by pafnuty** [comment]
>Ведь 99% данных - это строки! Поэтому можно писать просто ? или :name не запариваться с типами. А тип писать только там, где строка не подходит:

полностью поддерживаю!

Думаю с двумя буквами будет даже лучше, чем с двумя вопросами, более очевидно. По типу как с обозначениями пунктов или номеров (пп и №№ соответственно) в обычной жизни.

**Comment by GZep** [comment]
Вот на мой взгляд отличный железобетонный вариант: заглавные буквы для множеств!
Пример:
```
?s - строка
?S - строки
?i - число
?I - множество чисел
?n - имя поля
?N - множество имен полей
...
```
Идея с дефолтным ? без указателя для строк мне не нравится, экономия одного символа, чтобы лишний раз лезть в документацию. К тому же явно не понятно, что подразумеваются строки. Логически скорее ?p нужно поменять на ?, показывая, что какая-либо фильтрация по типу не требуется.
> 99% данных - это строки
50/50 числа постоянно используются для id. Простейшая выборка из базы по id идет.

**Comment by colshrapnel** [comment]
@GZep смотри.
Либа существует не сама по себе, а среди многих других.
Поэтому я стараюсь ориентироваться на существующие стандарты.
Если человек всегда писал просто ? для строк, то ему сложнее переучиваться на что-то другое. И, кстати, в этом смысле, ?p делать просто ? - это будет натуральная катастрофа :)

Тем более что я не собираюсь отказываться от ?s - ? будет просто алиасом, строку можно будет задать двумя способами.

По поводу же id - как раз здесь строка очень даже подходит. 
Передавать id как строку в запрос не представляет н единой проблемы.
И пользователи PDO как  раз постоянно это делают, обрабатывая 99% своих плейсхолдеров как строки. Это реально удобно и я дико жалею, что не сообразил ввести ? как синоним ?s рань раньше.

**Comment by GZep** [comment]
> Передавать id как строку в запрос не представляет н единой проблемы.

до тех пор, пока случайно не попадет строка и сиди гадай почему всегда пустой результат.

> пользователи PDO как раз постоянно это делают, обрабатывая 99% своих плейсхолдеров как строки

это php, тут только начато движение к строгой типизации. Ничего хорошего в том, что используют в данном случае строки нет, вообще низкое качество кода на php ни для кого не новость.

В каких библиотеках **?** использует в связке с синонимом? Есть-ли смысл экономить символ, часть разработчиков будет один вариант, часть другой. Не разумней-ли применять один паттерн? (смотря вперед: PSR, типизация)

Что на счет заглавных указателей для множеств?
