### ISSUE TITLE
numRows not working on row 183

### ISSUE THREAD

**Issue by kkhouani** [colshrapnel/safemysql#33]
returns: Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given

**Comment by harrydenley** [comment]
It means your query (`mysqli_query()`) failed, resulting in `false`. Effectively, you've done this; `$safeMySQL->numRows(false);`. It's not an issue with the class - but with your logic; you're not checking the query was successful before moving on.

If needed, alter the function to;

```
	public function numRows($result)
	{
                if( is_bool($result) ) {
                       return 0;
                }

		return mysqli_num_rows($result);
	}
```

But that's kind of cheating.
