### ISSUE TITLE
How to use the $db->getOne() query

### ISSUE THREAD

**Issue by dalai-lamia** [colshrapnel/safemysql#36]
I have tried to use the **$db->getOne();** query but I can't get it to work. Perhaps I'm doing something wrong, so I'd appreciate it if someone gives a clear example.

My query:
`$client = $db->getOne("SELECT ?n FROM ?n WHERE clientID = ?i", 'clientname', 'project_clients', $_GET['clientID']);`

Then I try to use the result as follows:
`$clientName = $client->clientname;`
but I get **Notice: Undefined property: stdClass::$clientname**

**Comment by dalai-lamia** [comment]
Oh, never mind! Incidentally found the answer in a [semi-related post](http://stackoverflow.com/a/25683814/1754033) on Stackoverflow:

`$clientName = $client->scalar;`

It would have never occurred to me (I'm not an expert) that I should use "scalar" instead of the field name.

**Comment by pafnuty** [comment]
```
$client = $db->getRow("SELECT ?n FROM ?n WHERE clientID = ?i", 'clientname', 'project_clients', $_GET['clientID']);
$clientName = $client['name'];
```

**Comment by dalai-lamia** [comment]
The correct way to get the result out of a getRow() query is **not** `$clientName = $client['clientname'];` This returns: "Fatal error: Cannot use object of type stdClass as array in..."

The correct way for a getRow() query is `$clientName = $client->clientname;`

But I **wasn't** asking about getRow() as I know how to use it. I was asking about getOne().

**Comment by colshrapnel** [comment]
It's just

    $clientname = $db->getOne("SELECT ?n FROM ?n WHERE clientID = ?i", 'clientname', 'project_clients', $_GET['clientID']);

And you already have clientname right in the `$clientname` variable:

    echo $clientname;

**Comment by dalai-lamia** [comment]
It doesn't work for me. I get: "Catchable fatal error: Object of class stdClass could not be converted to string in..."
This could be because I am using a modified version of your SafeMySQL class, the one that can be found here: https://github.com/ionutvmi/master-login-system

**Comment by colshrapnel** [comment]
I see. Looks like this issue should have been posted there. 

Anyway, glad you sorted it out!
