### ISSUE TITLE
How to close properly?

### ISSUE THREAD

**Issue by LucasPaganini** [colshrapnel/safemysql#42]
Should I just close as a regular connection?

`$db  = new SafeMySQL($opts);`
`mysqli_close($db);`

**Comment by colshrapnel** [comment]
Hello Lucas!

Just assign $db to NULL:

```$db = new SafeMySQL($opts);
$db= null; // closed```

But most of time you don't have to close the connection manually as it will be closed automatically at the end of the script execution

**Comment by LucasPaganini** [comment]
Thanks! Btw, your class is AWESOME!! 

I spent 2 days analyzing each line of code and I learned a lot, thanks you for the great work!!
