### ISSUE TITLE
Some url parameters have the same parts as placeholders

### ISSUE THREAD

**Issue by jzavorohina** [colshrapnel/safemysql#45]
I have tried to save html text with hyperlink but hyperlink (to popular web store) have the same part as placeholder - ?s, like this - _index.php?spm=2114_
So it throws an exception - _Number of args (0) doesn't match number of placeholders (1)_
I have tried to change regular expression - '~(\?[nsiuap])~u' to '~(\?[nsiuap]{1}[^a-z])~u'
But it work only on regex101.com

**Comment by alexprey** [comment]
You are sure that inserts data by correct way?

**Comment by jzavorohina** [comment]
For example:
_$safemysql->query("UPDATE table SET text='http://aliexpress.com/index.php?spm=2114'");_
There is no placeholders, but we can see - '?s' and it makes error:
_Number of args (0) doesn't match number of placeholders (1)_

**Comment by alexprey** [comment]
Yes, this code is not working, your should use the next approach for it:
```
$safemysql->query("UPDATE table SET text = ?s", "http://aliexpress.com/index.php?spm=2114");
````
And it should be used for any data that used for sql query.

**Comment by jzavorohina** [comment]
Good idea! Thanks a lot!
