### ISSUE TITLE
Could you please update composer package?

### ISSUE THREAD

**Issue by whisperstars** [colshrapnel/safemysql#49]
Hello, thanks for this class!
Your last change private field to protected was very useful for an extension.
But if dev used composer them can't take this changes.
So could you please update composer package?

**Comment by colshrapnel** [comment]
that's a very good idea but I seems unable to do so. 
Still trying but could use some help.

**Comment by lcherone** [comment]
You should remove `"version": "1.0.0"` from the `composer.json` and instead just use semvar tags as your doing, packagist will pick them up automatically.

To setup this repo with packagist:
- Head over to packagist and grab your token from your profile.
- Goto https://github.com/colshrapnel/safemysql/settings/installations and add packagist (click add service and find it), then with your packagist username (mopvhs) and the token add it.

Then when you tag a version of this lib, packagist will update.. else your need to go to packagist each time the big update button. You still need to use tags though.

See my SO answer if you need pictures ;p https://stackoverflow.com/questions/48316610/composer-require-without-dev-master/48317157#48317157

Maybe it helps.

**Comment by colshrapnel** [comment]
@lcherone thank you a lot for this guide!

Actually mopvhs is not my account and I have no idea who it is. So I reclaimed the ownership and now I can update the package. By the way it was just amazing experience talking to Packagist support!

So now it works, I can update the package.
I removed the explicit version as you said, but when I am doing ```composer require colshrapnel/safemysql```, it still takes the old version, creating composer.json

    {
        "require": {
            "colshrapnel/safemysql": "^1.0"
        }
    }

only if I change ^1.0 to dev-master it gets me the latest version.

Should I put something like ```"version": "dev-master"``` to composer.json file in the package?

**Comment by lcherone** [comment]
The best way is to not have any version defined in this projects composer.json

Allow the consumers to use `"minimum-stability": "dev"` if they want the master branch, not a release tag e.g the semvar.

Each time you add a tag, it will update on packagist. `^1.0` is anything after `1.0` but not `dev/master`. So if you did:

```
// tag it
git tag -a v1.0.0 -m "Comment for version 1.0.0"

// push it
git push origin v1.0.0
```

User downloads 1.0.0, complains somethings broke on an issue ;p..

Do your changes/fixes, push them as normal, then tag your release..
```
// tag it
git tag -a v1.0.1 -m "Comment for version 1.0.1"

// push it
git push origin v1.0.1
```

Then to update, the user would do `composer update`, and it would pull down `v1.0.1`

Look into using semvar, e.g `0.0.0`(major, minor, patch) not `0.0` (major, minor).. then you can do release patches before minor releases.. majors are new versions which may have breaking changes.. It makes life somewhat easier.

Hope it helps.

**Comment by lcherone** [comment]
For you, as the developer, you would have a `composer.json` file like:

```
{
    "minimum-stability": "dev",
    "require": {
        "colshrapnel/safemysql": "master"
    }
}
```

**Comment by colshrapnel** [comment]
Finally I made it! 

```composer require colshrapnel/safemysql``` now installs the latest version

Thank you @whisperstars for opening the issue and @lcherone for your enormous help!
