### ISSUE TITLE
Проблема с array_merge ?

### ISSUE THREAD

**Issue by KiraSokolov** [colshrapnel/safemysql#52]
В функцию передаю
```
 $array = array(
        "id" => "4",
        "teap" => "1251",
    );
    serviceActivity("delete", $array);
```
```
function serviceActivity ($action, $dataArray) 
{
    if ($action == "delete") {
        $date = date('Y-m-d H:i:s');
        
        $id = $dataArray['id'];
        $db = new SafeMySQL($db_opts);
        d($dataArray);
        $db->query("update service set deletedAt =?s  WHERE id=?i", $date, $id);
        echo "DONE!!!";
    }

}
```
И получаю : 
![2018-09-30_17-38-08](https://user-images.githubusercontent.com/6352214/46258683-ab8da680-c4d7-11e8-9143-af4feaca3b89.png)

**Comment by voxabucher** [comment]
You have empty array $db_opts. Get an array like this:
```
class MyClass {

  private $db_opts = array(
            'user'    => 'user',
            'pass'    => 'pass',
            'db'      => 'db',
            'charset' => 'latin1'
          );

  function serviceActivity ($action, $dataArray) 
  {
      if ($action == "delete") {
          $date = date('Y-m-d H:i:s');
          
          $id = $dataArray['id'];
          $db = new SafeMySQL($this->$db_opts);
          d($dataArray);
          $db->query("update service set deletedAt =?s  WHERE id=?i", $date, $id);
          echo "DONE!!!";
      }

  }
}
```

**Comment by KiraSokolov** [comment]
> You have empty array $db_opts. Get an array like this:
> 
> ```
> class MyClass {
> 
>   private $db_opts = array(
>             'user'    => 'user',
>             'pass'    => 'pass',
>             'db'      => 'db',
>             'charset' => 'latin1'
>           );
> 
>   function serviceActivity ($action, $dataArray) 
>   {
>       if ($action == "delete") {
>           $date = date('Y-m-d H:i:s');
>           
>           $id = $dataArray['id'];
>           $db = new SafeMySQL($this->$db_opts);
>           d($dataArray);
>           $db->query("update service set deletedAt =?s  WHERE id=?i", $date, $id);
>           echo "DONE!!!";
>       }
> 
>   }
> }
> ```

my bad, thanks)
