### ISSUE TITLE
Возникает странная ошибка

### ISSUE THREAD

**Issue by evgeniyefimchenko** [colshrapnel/safemysql#58]
Доброе время суток. Спасибо за отличное решение для работы с БД!
Возникла следующая проблема:
вызов функции:
`	public function is_alias_exist($alias_text) {
		gettype($alias_text); // string
		gettype(self::PAGES_TABLE); // string
		$sql = 'SELECT `id` FROM ?n WHERE `alias` LIKE ?s';
		return SafeMySQL::gi()->getOne($sql, self::PAGES_TABLE, $alias_text);
	}`

Всегда возвращает ошибку:
Warning: mysqli_real_escape_string() expects parameter 2 to be string, array given in /home/whrgijws/public_html/test/classes/plugins/safemysql.php on line 521

Подскажите в чём может быть проблема?
Заранее благодарен, Спасибо!

**Comment by in4s** [comment]
У Вас очень старнный код. Статический метод gi Вы сами создавали?

Вообще, без Вашего кода навряд ли кто-то сможет помочь.

**Comment by tolanych** [comment]
Да, по кофейной гуще пока не научились гадать.
Проверьте через отладчик (если нет - по старинке распечатайте var_dump-ом), в какой момент внутри цепочки вызовов переданная переменная $alias_text стала массивом, а не строкой. Ошибка сообщает об этом.

**Comment by in4s** [comment]
> Да, по кофейной гуще пока не научились гадать.
> Проверьте через отладчик (если нет - по старинке распечатайте var_dump-ом), в какой момент внутри цепочки вызовов переданная переменная $alias_text стала массивом, а не строкой. Ошибка сообщает об этом.

А как Вы определили что именно $alias_text становится массивом?

**Comment by evgeniyefimchenko** [comment]
> У Вас очень старнный код. Статический метод gi Вы сами создавали?
> 
> Вообще, без Вашего кода навряд ли кто-то сможет помочь.
Обычный синглтон добавил для удобства использования
`abstract class Singleton {
    private static $_aInstances = array();
    public static function getInstance() {
        $sClassName = get_called_class();
        if (class_exists($sClassName)) {
            if (!isset(self::$_aInstances[$sClassName]))
                self::$_aInstances[$sClassName] = new $sClassName();
            return self::$_aInstances[$sClassName];
        }
        return 0;
    }
    // более удобный вызов метода getInstance
    public static function gI() {
        return self::getInstance();
    }
}`
Удивительно что даже приведение типов не спасает.
Во всех остальных частях проекта работает как должно.
 
SafeMySQL::gi()->getOne($sql, self::PAGES_TABLE, (string)$alias_text);

**Comment by evgeniyefimchenko** [comment]
Дичь конечно дичайшая. Но преобразование файла документа в UTF-8 с BOM Устранило проблему.
