### ISSUE TITLE
Проверить возможность подключения к БД

### ISSUE THREAD

**Issue by evgeniyefimchenko** [colshrapnel/safemysql#62]
Доброго времени суток.
Я использую Ваш класс в своём проекте и на определённом этапе необходимо проверить возможность подключения к БД с переданными параметрами в конструктор.
`$db = new SafeMySQL(ENV_DB_HOST, ENV_DB_USER, ENV_DB_PASS, ENV_DB_NAME);`
Если к примеру передать неверного пользователя то вылетит ошибка `SafeMySQL: 1045 Access denied for user ...`
Как возможно перехватить ошибку подключения. try catch в данном случае не работает.

**Comment by justscribe** [comment]
errmode = 'error'
