### ISSUE TITLE
submitting a post in my site by user not showing properly. 

### ISSUE THREAD

**Issue by knimon** [colshrapnel/safemysql#63]
I have a member based site. recently I uploaded it in a hosting service provider.

my site was working fine in XAMPP in my computer. but in online hosting, whenever user create account for first time and if they submit a post, it don't show properly. but after some time it works well.

i am using not null for all my mysql table field. but there are some field which can be remain null. 
is the not null cell (which can be remain null) of table are the problem?

**Comment by colshrapnel** [comment]
Hello.

It's hard to tell based on such a scarce information.
What does it mean "don't show properly"?
What does it mean "after some time it works well"? It means after some time the submitted post appears somehow or after some time a new user gets the ability to post?

**Comment by knimon** [comment]
don't show properly means - the post apperars. but like/comment button don't appear in profile page. and in home page the post doesn't appear at all.

after some time it work means - after 12/24 hour the like/comment button appear in profile page. and the post also appear in the home page.

and after one post appear perfectly in home & profile page... every other submitted post after that appear instantly after submitting.  

can you help? plz.
