### ISSUE TITLE
как сделать ограничение вывода текста из базы?

### ISSUE THREAD

**Issue by No4NaMe** [colshrapnel/safemysql#65]
как сделать ограничение вывода текста из базы, это нужно если данные в базе слишком длинные и вывести нужно их в виде 50строк а дальше ... как это организовать большое спасибо!

**Comment by evgeniyefimchenko** [comment]
/**
     * Обрезает строку 
     * @param str $string - строка
     * @param int $len - количество символов
     * @return string обрезанная строка
     */
    public static function truncate_string($string, $len = 140) {
        $string = mb_substr(strip_tags($string), 0, $len);		
        $string = rtrim($string, "!,.-");		
        $string = mb_substr($string, 0, strrpos($string, ' '));
        return $string . "…";
    }

**Comment by 00dev** [comment]
> как сделать ограничение вывода текста из базы, это нужно если данные в базе слишком длинные и вывести нужно их в виде 50строк а дальше ... как это организовать большое спасибо!

Как этот вопрос связан с SafeMySQL?
